# -*- coding: utf-8 -*-
"""Global Indicators Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZmKxh0RCNQhjMdbDnWIpPHCC2SM2Zc8

#Load Data
"""

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('world-data-2023.csv')

data

"""#Comparative Analysis of GDP, Life Expectancy, and Unemployment Rate"""

# Select relevant columns for comparative analysis
columns = ['Country', 'GDP', 'Life expectancy', 'Unemployment rate']
comparative_data = data[columns]
comparative_data.to_csv('comparative_data.csv', index=False)

comparative_data

# Calculate descriptive statistics for each column
statistics = comparative_data.describe()
statistics.to_csv('statistics.csv', index=False)

statistics

# Compare countries based on GDP
gdp_ranking = comparative_data.sort_values('GDP', ascending=False)
gdp_ranking.to_csv('gdp_ranking.csv', index=False)

gdp_ranking

# Compare countries based on life expectancy
life_expectancy_ranking = comparative_data.sort_values('Life expectancy', ascending=False)
life_expectancy_ranking.to_csv('life_expectancy_ranking.csv', index=False)

life_expectancy_ranking

top30_life_expectancy = life_expectancy_ranking.head(30)
plt.figure(figsize=(15, 6))  # Set the figure size
top30_life_expectancy.plot(x='Country', y='Life expectancy', kind='bar')
plt.title('Top 30 Countries - Life Expectancy')
plt.xlabel('Country')
plt.ylabel('Life Expectancy')
plt.xticks(rotation=90)
plt.tight_layout()  # Adjust spacing
plt.savefig('top30_life_expectancy_graph.png')

# Compare countries based on unemployment rate
unemployment_ranking = comparative_data.sort_values('Unemployment rate')
unemployment_ranking.to_csv('unemployment_ranking.csv', index=False)

unemployment_ranking

"""#Demographic Analysis of Top 20 Countries"""

# Select relevant columns for demographic analysis
columns = ['Country', 'Birth Rate', 'Infant mortality', 'Urban_population']
demographic_data = data[columns]

# Make a copy of the DataFrame to avoid the warning
demographic_data = demographic_data.copy()

# Sort data by Birth Rate in descending order
demographic_data.sort_values('Birth Rate', ascending=False, inplace=True)

# Take top 20 entries
demographic_data_top20 = demographic_data.head(20)

# Analyze birth rate
birth_rate_statistics = demographic_data_top20['Birth Rate'].describe()
birth_rate_statistics.to_csv('birth_rate_statistics.csv')

birth_rate_statistics

# Generate birth rate graph
demographic_data_top20.plot(x='Country', y='Birth Rate', kind='bar')
plt.title('Top 20 Countries - Birth Rate')
plt.xlabel('Country')
plt.ylabel('Birth Rate')
plt.xticks(rotation=90)
plt.savefig('birth_rate_graph.png')

# Analyze infant mortality rate
infant_mortality_statistics = demographic_data_top20['Infant mortality'].describe()
infant_mortality_statistics.to_csv('infant_mortality_statistics.csv')

infant_mortality_statistics

# Generate infant mortality rate graph
demographic_data_top20.plot(x='Country', y='Infant mortality', kind='bar')
plt.title('Top 20 Countries - Infant Mortality Rate')
plt.xlabel('Country')
plt.ylabel('Infant Mortality Rate')
plt.xticks(rotation=90)
plt.savefig('infant_mortality_graph.png')

# Analyze urban/rural distribution
urban_rural_distribution = demographic_data_top20.groupby('Urban_population').size()
urban_rural_distribution.to_csv('urban_rural_distribution.csv')

urban_rural_distribution

# Generate urban/rural distribution graph
urban_rural_distribution.plot(kind='pie', autopct='%1.1f%%')
plt.title('Top 20 Countries - Urban vs Rural Population Distribution')
plt.ylabel('')
plt.savefig('urban_rural_distribution_graph.png')

"""#Environmental Analysis of CO2 Emissions, Forested Area, and Agricultural Land"""

# Select relevant columns for environmental analysis
columns = ['Country', 'Co2-Emissions', 'Forested Area (%)', 'Agricultural Land( %)']
environmental_data = data[columns]

# Analyze CO2 emissions
co2_emissions_statistics = environmental_data['Co2-Emissions'].describe()
co2_emissions_statistics.to_csv('co2_emissions_statistics.csv')

co2_emissions_statistics

# Analyze forested area
forested_area_statistics = environmental_data['Forested Area (%)'].describe()
forested_area_statistics.to_csv('forested_area_statistics.csv')

forested_area_statistics

# Analyze agricultural land
agricultural_land_statistics = environmental_data['Agricultural Land( %)'].describe()
agricultural_land_statistics.to_csv('agricultural_land_statistics.csv')

agricultural_land_statistics

"""#Health Analysis of Life Expectancy, Infant Mortality, Maternal Mortality, and Health Expenditure"""

# Select relevant columns for health analysis
columns = ['Country', 'Life expectancy', 'Infant mortality', 'Maternal mortality ratio', 'Out of pocket health expenditure']
health_data = data[columns]

# Analyze life expectancy
life_expectancy_statistics = health_data['Life expectancy'].describe()
life_expectancy_statistics.to_csv('life_expectancy_statistics.csv')

life_expectancy_statistics

# Life expectancy graph
top30_life_expectancy = health_data.nlargest(30, 'Life expectancy')
top30_life_expectancy.plot(x='Country', y='Life expectancy', kind='bar')
plt.title('Top 30 Countries - Life Expectancy')
plt.xlabel('Country')
plt.ylabel('Life Expectancy')
plt.xticks(rotation=90)
plt.savefig('life_expectancy_graph.png')

# Analyze infant mortality rate
infant_mortality_statistics = health_data['Infant mortality'].describe()
infant_mortality_statistics.to_csv('infant_mortality_statistics.csv')

infant_mortality_statistics

# Infant mortality rate graph
top30_infant_mortality = health_data.nsmallest(30, 'Infant mortality')
top30_infant_mortality.plot(x='Country', y='Infant mortality', kind='bar')
plt.title('Top 30 Countries - Infant Mortality Rate')
plt.xlabel('Country')
plt.ylabel('Infant Mortality Rate')
plt.xticks(rotation=90)
plt.savefig('infant_mortality_graph.png')

# Analyze maternal mortality ratio
maternal_mortality_statistics = health_data['Maternal mortality ratio'].describe()
maternal_mortality_statistics.to_csv('maternal_mortality_statistics.csv')

maternal_mortality_statistics

# Maternal mortality ratio graph
top30_maternal_mortality = health_data.nlargest(30, 'Maternal mortality ratio')
top30_maternal_mortality.plot(x='Country', y='Maternal mortality ratio', kind='bar')
plt.title('Top 30 Countries - Maternal Mortality Ratio')
plt.xlabel('Country')
plt.ylabel('Maternal Mortality Ratio')
plt.xticks(rotation=90)
plt.savefig('maternal_mortality_graph.png')

# Analyze out-of-pocket health expenditure
out_of_pocket_expenditure_statistics = health_data['Out of pocket health expenditure'].describe()
out_of_pocket_expenditure_statistics.to_csv('out_of_pocket_expenditure_statistics.csv')

out_of_pocket_expenditure_statistics

"""#Educational Analysis of Primary and Tertiary School Enrollment"""

# Select relevant columns for educational analysis
columns = ['Country', 'Gross primary education enrollment (%)', 'Gross tertiary education enrollment (%)']
educational_data = data[columns]

# Analyze primary school enrollment rate
primary_enrollment_statistics = educational_data['Gross primary education enrollment (%)'].describe()
primary_enrollment_statistics.to_csv('primary_enrollment_statistics.csv')

primary_enrollment_statistics

# Analyze tertiary school enrollment rate
tertiary_enrollment_statistics = educational_data['Gross tertiary education enrollment (%)'].describe()
tertiary_enrollment_statistics.to_csv('tertiary_enrollment_statistics.csv')

tertiary_enrollment_statistics

"""#Labor Market Analysis"""

# Select relevant columns for labor market analysis
columns = ['Country', 'Population: Labor force participation (%)', 'Unemployment rate', 'Armed Forces size']
labor_market_data = data[columns]

# Analyze labor force participation rate
labor_force_participation_statistics = labor_market_data['Population: Labor force participation (%)'].describe()
labor_force_participation_statistics.to_csv('labor_force_participation_statistics.csv')

labor_force_participation_statistics

# Analyze unemployment rate
unemployment_rate_statistics = labor_market_data['Unemployment rate'].describe()
unemployment_rate_statistics.to_csv('unemployment_rate_statistics.csv')

unemployment_rate_statistics

# Analyze armed forces size
armed_forces_size_statistics = labor_market_data['Armed Forces size'].describe()
armed_forces_size_statistics.to_csv('armed_forces_size_statistics.csv')

armed_forces_size_statistics

"""#Tax Analysis"""

# Select relevant columns for tax analysis
columns = ['Country', 'Total tax rate', 'Tax revenue (%)']
tax_data = data[columns]

# Analyze total tax rate
total_tax_rate_statistics = tax_data['Total tax rate'].describe()
total_tax_rate_statistics.to_csv('total_tax_rate_statistics.csv')

total_tax_rate_statistics

# Analyze tax revenue
tax_revenue_statistics = tax_data['Tax revenue (%)'].describe()
tax_revenue_statistics.to_csv('tax_revenue_statistics.csv')

tax_revenue_statistics

"""#Urbanization Analysis"""

# Select relevant columns for urbanization analysis
columns = ['Country', 'Urban_population', 'Largest city']
urbanization_data = data[columns]

# Analyze urban population distribution
urban_population_distribution = urbanization_data.groupby('Urban_population').size()
urban_population_distribution.to_csv('urban_population_distribution.csv')

urban_population_distribution

# Analyze largest cities
largest_cities_statistics = urbanization_data['Largest city'].describe()
largest_cities_statistics.to_csv('largest_cities_statistics.csv')

largest_cities_statistics